INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (1, '', 'A', 'B', 'C', '');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (2, '1.', 'อัตราส่วนการตายมารดาไทยต่อการเกิดมีชีพแสนคน', '15', 'ต่อการมีชีพแสนคน', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (3, '2.', 'ร้อยละของเด็ก อายุ 0 - 5 ปี มีพัฒนาการสมวัย', '88', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (4, '4.', 'ร้อยละของเด็ก อายุ 0 – 5 ปี ฟันดีไม่มีผุ (Cavity Free)', '80', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (5, '5.', 'ร้อยละของชุมชนมีการดำเนินการจัดการสุขภาพที่เหมาะสมกับประชาชน', '90', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (6, '6.', 'อัตราความรอบรู้ด้านสุขภาพของประชาชนไทย อายุ 15 ปี ขึ้นไป', '92.93', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (7, '7.', '1 ร้อยละการตรวจติดตามยืนยันวินิจฉัยป่วยโรคเบาหวาน', '70', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (8, '7.', '2 ร้อยละการตรวจติดตามยืนยันวิจัยกลุ่มสงสัยป่วยโรคความดันโลหิตสูง', '80', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (9, '7.', '3 ร้อยละผู้ป่วยโรคเบาหวานที่ควบคุมน้ำตาลได้ดี', '40', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (10, '7.', '4 ร้อยละผู้ป่วยโรคความดันโลหิตสูงที่ควบคุมความดันโลหิตสูงได้ดี', '60', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (11, '7.', '5 ร้อยละผู้ป่วยโรคเบาหวานชนิดที่ 2 ที่เข้าสู่เปาหวานระยะสงบ (DM remisiom)', '10', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (12, '8.', 'อัตราการเสียชีวิตและบาดเจ็บจากอุบัติเหตุทางถนนใน กลุ่มเด็กและเยาวชน (ช่วงวัย 1-18 ปี) ลดลง', '-3', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (13, '9.', 'ร้อยละความครอบคลุมของวัคซีนป้องกันหัด-คางทูม-หัดเยอรมัน เข็มที่ 2 (MMR2) ในเด็กอายุต่ำกว่า 3 ปี ระดับจังหวัด เป็นไปตามเป้าหมายการกำจัดโรคหัดตามพันธสัญญานานาชาติ', '95', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (14, '10.', '1 ร้อยละของโรงพยาบาลที่พัฒนาอนามัยสิ่งแวดล้อมได้ตามเกณฑ์ GCHC (ระดับมาตรฐานขึ้นไป)', '95', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (15, '10.', '2 ร้อยละของโรงพยาบาลที่พัฒนาอนามัยสิ่งแวดล้อมได้ตามเกณฑ์GCHC (ระดับท้าทาย)', '30', 'ร้อยละ', 'ประเด็นที่ 1 : ส่งเสริมสุขภาพ ป้องกันโรคและคุ้มครองผู้บริโภคเป็นเลิศ (PP & P Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (16, '12.', 'อัตราตายผู้ป่วยติดเชื้อในกระแสเลือดแบบรุนแรงชนิด community-acquired', '24', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (17, '14.', 'อัตราตายของผู้ป่วยโรคหลอดเลือดสมอง (Stroke; I60 - I64)', '7', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (18, '14.', '1 ร้อยละผู้ป่วยโรคหลอดเลือดสมอง (160-164) ท่ีมีอาการไม่เกิน 72 ชั่วโมง ได้รับการรักษาใน Stroke Unit', '80', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (19, '15.', '1 อัตราตายของผู้ป่วยโรคกล้ามเนื้อหัวใจตายเฉียบพลันชนิด STEMI', '8', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (20, '15.', '2 ร้อยละของการให้การรักษาผู้ป่วย STEMI ได้ตามมาตรฐานเวลาที่กำหนด', '70', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (21, '15.2.', '1 ร้อยละของผู้ป่วย STEMI ที่ได้รับยาละลายลิ่มเลือดได้ตามมาตรฐานเวลาที่กำหนด หรือ', '70', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (22, '15.2.', '2 ร้อยละของผู้ป่วย STEMI ที่ได้รับการทำ Primary PCI ได้ตามมาตรฐานเวลาที่กำหนด', '70', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (23, '15.', '3 อัตราตายของผู้ป่วยโรคกล้ามเนื้อหัวใจตายเฉียบพลันชนิด STEMI ภายใน 30 วัน นับจากผู้ป่วยได้รับ การวินิจฉัย STEMI', '9', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (24, '16.', 'อัตราตายทารกแรกเกิดอายุน้อยกว่าหรือเท่ากับ 28 วัน', '3.6', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (25, '16.', '1 จำนวนเตียง NICU ในเขตสุขภาพ', '300', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (26, '16.', '2 ร้อยละของการใช้นมแม่ Exclusive breastfeeding ในทารกป่วยเมื่อกลับบ้าน', '65', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (27, '17.', 'ร้อยละความครอบคลุมการคัดกรองการได้ยินของทารกแรกเกิด', '95', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (28, '18.', '1 ค่าเฉลี่ยคะแนนถ่วงน้ำหนักของความพร้อมด้านทรัพยากรและระบบการดูแลผูป่วย palliative care ของ โรงพยาบาลในจังหวัด', '4', 'ค่าเฉลี่ยคะแนนถ่วงน้ำหนัก', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (29, '18.', '2 ร้อยละของผู้ป่วยผู้ใหญ่สามารถเข้าถึงบริการ Palliative Care (เมื่อเทียบกับค่าคาดการณ์); Accessibility', '80', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (30, '18.', '3 ร้อยละของผู้ป่วยเด็กสามารถเข้าถึงบริการ Palliative Care (เมื่อเทียบกับค่าคาดการณ์); Accessibility', '50', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (31, '18.', '4 ร้อยละของผู้ป่วย Palliative Care ได้รับบริการดูแลต่อเนื่องที่บ้าน/ชุมชน', '55', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (32, '18.', '5 ร้อยละของผู้ป่วย palliative care ที่ได้รับการทำ family meeting และ Advance Care Planning', '85', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (33, '18.', '6 อัตราประชากรที่จัดทำ Living Will (ต่อประชากร 1,000 คน)', '15', '15 ต่อพันประชากร', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (34, '18.', '7 ร้อยละของผู้ป่วยประคับประคอง (Palliative Care) ที่ได้รับการดูแลตามแผนดูแลล่วงหน้า (ACP) อย่างมีคุณภาพ โดยมีสถานที่เสียชีวิตเป็นไปตามความประสงค์ (Preferred Place of Death)', '60', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (35, '18.', '8 ร้อยละของผู้ป่วยกลุ่มโรคมะเร็งระยะประคับประคอง ICD-10 รหัส C00-C96 หรือ D37-D48 ที่ได้รับการจัดการอาการปวด และ/หรือ อาการรบกวน โดยใช้ Opioid (ติดตามผลการดำเนินการจาก HDC Workload)', '55', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (36, '18.', '9 ร้อยละของโรงพยาบาลที่ให้บริการ Home ward for active dying patient', '80', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (37, '20.', '1 ร้อยละของผู้ป่วยที่ได้รับการรักษาด้วยการผ่าตัดภายในระยะเวลา 4 สัปดาห์', '70', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (38, '20.', '2 ร้อยละของผู้ป่วยที่ได้รับการรักษาด้วยเคมีบําบัดภายในระยะเวลา 6 สัปดาห์', '70', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (39, '20.', '3 ร้อยละของผู้ป่วยที่ได้รับการรักษาด้วยรังสีรักษาภายในระยะเวลา 6 สัปดาห์', '60', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (40, '22.', '1 ร้อยละของผู้เสียชีวิตจากการฆ่าตัวตายที่ลดลงเมื่อเทียบกับปีงบประมาณที่ผ่านมา', '10', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (41, '22.', '2 ร้อยละของผู้พยายามฆ่าตัวตายเข้าถึงบริการที่มีประสิทธิภาพ', '70', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (42, '23.', 'ร้อยละของผู้ป่วยยาเสพติดเข้าสู่กระบวนการบำบัดรักษา ได้รับการดูแลอย่างมีคุณภาพต่อเนื่องจนถึงการติดตาม (Retention Rate)', '75', 'ร้อยละ', 'ประเด็นที่ 2 : ระบบบริการสุขภาพเป็นเลิศ (Service Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (43, '24.', 'ร้อยละของเขตสุขภาพที่มีการบริหารจัดการกำลังคนเพื่อรองรับระบบบริการที่มีประสิทธิภาพ 1) สัดส่วนการกระจายแพทย์ในโรงพยาบาลชุมชนสังกัดสำนักงานปลัดกระทรวงสาธารณสุข', '80', 'ร้อยละ', 'ประเด็นที่ 3 : บุคลากรเป็นเลิศ (People Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (44, '26.', 'ร้อยละของโรงพยาบาลในเขตสุขภาพผ่านเกณฑ์พัฒนา โรงพยาบาลที่มีการตรวจทางห้องปฏิบัติการอย่างสมเหตุผล (RLU hospital Plus) ตามที่กำหนด', '50', 'ร้อยละ', 'ประเด็นที่ 4 : บริหารเป็นเลิศด้วยธรรมาภิบาล (Governance Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (45, '27.', 'ร้อยละของหน่วยบริการที่ผ่านเกณฑ์การประเมินประสิทธิภาพ Total Performance Score (TPS)', '55', 'ร้อยละ', 'ประเด็นที่ 4 : บริหารเป็นเลิศด้วยธรรมาภิบาล (Governance Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (46, '28.', 'อัตราการเพิ่มขึ้นของจำนวนสถานประกอบการด้านการท่องเที่ยวเชิงสุขภาพที่ได้รับมาตรฐานตามที่กำหนด', '1', 'แห่ง', 'ประเด็นที่ 4 : บริหารเป็นเลิศด้วยธรรมาภิบาล (Governance Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (47, '29.', 'ร้อยละผลิตภัณฑ์สุขภาพชุมชนได้รับการอนุญาต *เพิ่มขึ้นร้อยละ 10 จากปี พ.ศ. 2568', '100', 'ร้อยละ', 'ประเด็นที่ 4 : บริหารเป็นเลิศด้วยธรรมาภิบาล (Governance Excellence)');
INSERT INTO public.kpis (id, kpi_number, kpi_name, target, unit, category) VALUES (48, '30.', 'มูลค่าการใช้ยาสมุนไพรในสิทธิ UC', '125', 'ล้านบาท', 'ประเด็นที่ 4 : บริหารเป็นเลิศด้วยธรรมาภิบาล (Governance Excellence)');

INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (2, '10-2568', 287.36);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (2, '11-2568', 291.97);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (2, '12-2568', 201.82);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (2, '01-2569', 155.28);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (2, '02-2569', 193.42);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (2, '03-2569', 144.86);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (2, '04-2569', 138.76);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (2, '05-2569', 138.76);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (3, '10-2568', 42.67);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (3, '11-2568', 43.52);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (3, '12-2568', 43.43);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (3, '01-2569', 43.12);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (3, '02-2569', 43.57);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (3, '03-2569', 43.58);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (3, '04-2569', 41.83);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (3, '05-2569', 37.8);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (4, '02-2569', 77.33);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (4, '03-2569', 76.2);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (4, '04-2569', 75.8);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (4, '05-2569', 77.26);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (5, '10-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (5, '11-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (5, '12-2568', 97.62);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (5, '01-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (5, '02-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (5, '03-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (5, '04-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (5, '05-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (6, '10-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (6, '11-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (6, '12-2568', 97.73);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (6, '01-2569', 87.65);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (6, '02-2569', 85.51);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (6, '03-2569', 91.49);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (6, '04-2569', 92.36);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (6, '05-2569', 93.09);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (7, '03-2569', 52.97);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (7, '05-2569', 59.42);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (8, '03-2569', 72.9);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (8, '05-2569', 80.22);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (9, '03-2569', 27.37);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (9, '05-2569', 28.19);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (10, '03-2569', 49.15);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (10, '05-2569', 46.6);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (11, '05-2569', 20.29);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (12, '10-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (12, '11-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (12, '12-2568', 1.91);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (12, '01-2569', 3.75);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (12, '02-2569', 1.78);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (12, '03-2569', 15.26);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (12, '04-2569', 4.99);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (12, '05-2569', 6.99);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (13, '10-2568', 73.48);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (13, '11-2568', 68.54);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (13, '12-2568', 62.82);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (13, '01-2569', 63.11);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (13, '02-2569', 64.58);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (13, '03-2569', 68.66);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (13, '04-2569', 74.6);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (13, '05-2569', 77.15);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (14, '10-2568', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (14, '11-2568', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (14, '12-2568', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (14, '01-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (14, '02-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (14, '03-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (14, '04-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (14, '05-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (15, '10-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (15, '11-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (15, '12-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (15, '01-2569', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (15, '02-2569', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (15, '03-2569', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (15, '04-2569', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (15, '05-2569', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (16, '10-2568', 23);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (16, '11-2568', 20.83);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (16, '12-2568', 19.51);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (16, '01-2569', 17.07);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (16, '02-2569', 34.61);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (16, '03-2569', 17.64);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (16, '04-2569', 24.13);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (17, '10-2568', 11.7);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (17, '11-2568', 11.2);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (17, '12-2568', 10.5);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (17, '01-2569', 9.66);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (17, '02-2569', 6.48);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (17, '03-2569', 5.79);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (17, '04-2569', 12.25);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (18, '10-2568', 72.18);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (18, '11-2568', 80.28);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (18, '12-2568', 78.37);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (18, '01-2569', 81.25);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (18, '02-2569', 74.01);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (18, '03-2569', 72.84);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (18, '04-2569', 75.22);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (19, '10-2568', 9.5);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (19, '11-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (19, '12-2568', 10.7);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (19, '01-2569', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (19, '02-2569', 8.3);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (19, '03-2569', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (19, '04-2569', 12);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (20, '10-2568', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (20, '11-2568', 88.9);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (20, '12-2568', 90);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (20, '01-2569', 93);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (20, '02-2569', 94.5);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (20, '03-2569', 90);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (20, '04-2569', 85.5);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (21, '10-2568', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (21, '11-2568', 77.7);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (21, '12-2568', 80);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (21, '01-2569', 85.7);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (21, '02-2569', 88.8);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (21, '03-2569', 80);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (21, '04-2569', 71.4);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (22, '10-2568', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (22, '11-2568', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (22, '12-2568', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (22, '01-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (22, '02-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (22, '03-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (22, '04-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (23, '10-2568', 9.5);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (23, '11-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (23, '12-2568', 10.7);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (23, '01-2569', 4.35);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (23, '02-2569', 8.3);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (23, '03-2569', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (23, '04-2569', 12);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (24, '10-2568', 3.77);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (24, '11-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (24, '12-2568', 1.92);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (24, '01-2569', 2.23);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (24, '02-2569', 2.44);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (24, '03-2569', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (24, '04-2569', 4.32);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (25, '10-2568', 295);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (25, '11-2568', 297);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (25, '12-2568', 288);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (25, '01-2569', 249);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (25, '02-2569', 228);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (25, '03-2569', 260);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (25, '04-2569', 221);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (26, '10-2568', 87.67);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (26, '11-2568', 86.35);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (26, '12-2568', 89.41);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (26, '01-2569', 86.96);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (26, '02-2569', 86.45);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (26, '03-2569', 96.97);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (26, '04-2569', 94.14);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (27, '10-2568', 70.54);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (27, '11-2568', 72.87);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (27, '12-2568', 67.94);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (27, '01-2569', 70.44);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (27, '02-2569', 76.23);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (27, '03-2569', 81.95);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (27, '04-2569', 69.84);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (28, '10-2568', 1);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (28, '11-2568', 1);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (28, '12-2568', 1);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (28, '01-2569', 1);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (28, '02-2569', 1);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (28, '03-2569', 1);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (28, '04-2569', 1);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (29, '12-2568', 50);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (29, '03-2569', 50.02);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (29, '05-2569', 80.61);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (30, '12-2568', 14.86);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (30, '03-2569', 20.79);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (30, '05-2569', 21.78);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (31, '12-2568', 49);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (31, '03-2569', 38.08);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (31, '05-2569', 44.2);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (32, '12-2568', 94.27);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (32, '03-2569', 95.55);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (32, '05-2569', 95.09);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (33, '12-2568', 3.08);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (33, '03-2569', 3.08);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (33, '05-2569', 5.16);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (34, '12-2568', 89);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (34, '03-2569', 88.9);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (34, '05-2569', 87.1);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (35, '12-2568', 44.22);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (35, '03-2569', 58.36);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (35, '05-2569', 52.53);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (36, '12-2568', 6.25);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (36, '03-2569', 6.25);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (36, '05-2569', 37.5);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (37, '10-2568', 96.87);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (37, '11-2568', 89.28);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (37, '12-2568', 81.57);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (37, '01-2569', 81.08);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (37, '02-2569', 81.87);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (37, '03-2569', 83.05);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (37, '04-2569', 82.5);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (38, '10-2568', 89.47);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (38, '11-2568', 79.41);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (38, '12-2568', 77.14);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (38, '01-2569', 80.7);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (38, '02-2569', 73.8);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (38, '03-2569', 73.58);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (38, '04-2569', 73.8);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (39, '10-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (39, '11-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (39, '12-2568', 62.16);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (39, '01-2569', 62.16);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (39, '02-2569', 62.16);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (39, '03-2569', 62.16);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (39, '04-2569', 61.03);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (40, '05-2569', 3.69);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (41, '05-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (42, '10-2568', 86.89);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (42, '11-2568', 90.91);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (42, '12-2568', 89.12);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (42, '01-2569', 89.51);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (42, '02-2569', 89.19);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (42, '03-2569', 91.62);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (42, '04-2569', 92.09);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (42, '05-2569', 91.56);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (43, '10-2568', 78.57);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (43, '11-2568', 78.57);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (43, '12-2568', 78.57);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (43, '01-2569', 78.57);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (43, '02-2569', 78.57);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (43, '03-2569', 71.42);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (43, '04-2569', 71.42);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (43, '05-2569', 71.42);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (43, '06-2569', 71.42);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (43, '07-2569', 71.42);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (43, '08-2569', 71.42);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (43, '09-2569', 71.42);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (44, '10-2568', 50);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (44, '11-2568', 50);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (44, '12-2568', 50);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (44, '01-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (44, '02-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (44, '03-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (44, '04-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (45, '12-2568', 43.75);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (45, '03-2569', 62.5);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (46, '10-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (46, '11-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (46, '12-2568', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (46, '01-2569', 0);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (46, '02-2569', 1);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (46, '03-2569', 2);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (46, '04-2569', 2);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (46, '05-2569', 2);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (47, '10-2568', 23.81);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (47, '11-2568', 33.33);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (47, '12-2568', 52.38);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (47, '01-2569', 52.38);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (47, '02-2569', 71.43);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (47, '03-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (47, '04-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (47, '05-2569', 100);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (48, '10-2568', 1.5);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (48, '11-2568', 2.5);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (48, '12-2568', 3.09);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (48, '01-2569', 4.5);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (48, '02-2569', 5.52);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (48, '03-2569', 5.95);
INSERT INTO public.kpi_monthly_data (kpi_id, month_year, value) VALUES (48, '04-2569', 6.41);